In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

demo = pd.read_csv('../data/train_OwBvO8W/demographics.csv')
print(demo.shape)
demo.head()

(60, 3)

      Agency  Avg_Population_2017  Avg_Yearly_Household_Income_2017
0  Agency_05              3044268                            182944
1  Agency_02              3137874                            240809
2  Agency_55              2025793                            238553
3  Agency_53              1729177                            111048
4  Agency_50              2057678                            144594

In [2]:
event = pd.read_csv('../data/train_OwBvO8W/event_calendar.csv')
print(event.shape)
event.head()

(61, 13)

,YearMonth,Easter Day,Good Friday,New Year,Christmas,Labor Day,Independence Day,Revolution Day Memorial,Regional Games,FIFA U-17 World Cup,Football Gold Cup,Beer Capital,Music Fest
0,201301,0,0,1,0,0,0,0,0,0,0,0,0
1,201302,0,0,0,0,0,0,0,0,0,0,0,0
2,201303,1,1,0,0,0,0,0,0,0,0,0,1
3,201304,0,0,0,0,0,0,0,0,0,0,0,0
4,201305,0,0,0,0,1,0,0,0,0,0,0,0

In [3]:
historical = pd.read_csv('../data/train_OwBvO8W/historical_volume.csv')
print(historical.shape)
historical.head()

(21000, 4)

      Agency     SKU  YearMonth    Volume
0  Agency_22  SKU_01     201301   52.2720
1  Agency_22  SKU_02     201301  110.7000
2  Agency_58  SKU_23     201301    0.0000
3  Agency_48  SKU_07     201301   28.3200
4  Agency_22  SKU_05     201301  238.5387

In [4]:
soda = pd.read_csv('../data/train_OwBvO8W/industry_soda_sales.csv')
print(soda.shape)
soda.head()

(60, 2)

   YearMonth  Soda_Volume
0     201301    718394219
1     201302    753938444
2     201303    892192092
3     201304    838099501
4     201305    864420003

In [5]:
industry = pd.read_csv('../data/train_OwBvO8W/industry_volume.csv')
print(industry.shape)
industry.head()

(60, 2)

   YearMonth  Industry_Volume
0     201301        492612703
1     201302        431937346
2     201303        509281531
3     201304        532390389
4     201305        551755254

In [6]:
price = pd.read_csv('../data/train_OwBvO8W/price_sales_promotion.csv')
print(price.shape)
price.head()

(21000, 6)

      Agency     SKU  YearMonth        Price        Sales  Promotions
0  Agency_01  SKU_01     201301  1141.500000  1033.432731  108.067269
1  Agency_01  SKU_01     201302  1141.500000  1065.417195   76.082805
2  Agency_01  SKU_01     201303  1179.345820  1101.133633   78.212187
3  Agency_01  SKU_01     201304  1226.687500  1138.283357   88.404143
4  Agency_01  SKU_01     201305  1230.331104  1148.969634   81.361470

In [7]:
weather = pd.read_csv('../data/train_OwBvO8W/weather.csv')
print(weather.shape)
weather.head()

(3600, 3)

   YearMonth     Agency  Avg_Max_Temp
0     201301  Agency_01        17.072
1     201302  Agency_01        19.984
2     201303  Agency_01        24.600
3     201304  Agency_01        27.532
4     201305  Agency_01        29.396

In [8]:
sku = historical.merge(price,on=['Agency', 'SKU', 'YearMonth'],how='left')
sku = sku.merge(soda, on=['YearMonth'], how='left')
sku = sku.merge(industry, on='YearMonth', how='left')
sku = sku.merge(weather, on=['YearMonth', 'Agency'], how='left')
sku = sku.merge(event,on=['YearMonth'], how='left')
print(sku.shape)
sku.head()

(21000, 22)

,Agency,SKU,YearMonth,Volume,Price,Sales,Promotions,Soda_Volume,Industry_Volume,Avg_Max_Temp,...,New Year,Christmas,Labor Day,Independence Day,Revolution Day Memorial,Regional Games,FIFA U-17 World Cup,Football Gold Cup,Beer Capital,Music Fest
0,Agency_22,SKU_01,201301,52.2720,1168.903668,1069.166193,99.737475,718394219,492612703,25.845238,...,1,0,0,0,0,0,0,0,0,0
1,Agency_22,SKU_02,201301,110.7000,1167.000000,1067.257500,99.742500,718394219,492612703,25.845238,...,1,0,0,0,0,0,0,0,0,0
2,Agency_58,SKU_23,201301,0.0000,0.000000,0.000000,0.000000,718394219,492612703,22.219737,...,1,0,0,0,0,0,0,0,0,0
3,Agency_48,SKU_07,201301,28.3200,1143.503390,1143.503390,0.000000,718394219,492612703,24.052893,...,1,0,0,0,0,0,0,0,0,0
4,Agency_22,SKU_05,201301,238.5387,1310.176057,1203.875711,106.300346,718394219,492612703,25.845238,...,1,0,0,0,0,0,0,0,0,0

In [9]:
sku = sku.drop(['FIFA U-17 World Cup', 'Football Gold Cup'], axis=1)
sku['Month'] = sku['YearMonth'].apply(lambda x: str(x)[-2:])
sku.head()

,Agency,SKU,YearMonth,Volume,Price,Sales,Promotions,Soda_Volume,Industry_Volume,Avg_Max_Temp,...,Good Friday,New Year,Christmas,Labor Day,Independence Day,Revolution Day Memorial,Regional Games,Beer Capital,Music Fest,Month
0,Agency_22,SKU_01,201301,52.2720,1168.903668,1069.166193,99.737475,718394219,492612703,25.845238,...,0,1,0,0,0,0,0,0,0,01
1,Agency_22,SKU_02,201301,110.7000,1167.000000,1067.257500,99.742500,718394219,492612703,25.845238,...,0,1,0,0,0,0,0,0,0,01
2,Agency_58,SKU_23,201301,0.0000,0.000000,0.000000,0.000000,718394219,492612703,22.219737,...,0,1,0,0,0,0,0,0,0,01
3,Agency_48,SKU_07,201301,28.3200,1143.503390,1143.503390,0.000000,718394219,492612703,24.052893,...,0,1,0,0,0,0,0,0,0,01
4,Agency_22,SKU_05,201301,238.5387,1310.176057,1203.875711,106.300346,718394219,492612703,25.845238,...,0,1,0,0,0,0,0,0,0,01

In [10]:
from sklearn.preprocessing import OneHotEncoder, PowerTransformer, StandardScaler

month_onehot = pd.DataFrame(OneHotEncoder().fit_transform(sku[['Month']]).toarray(), columns=list(map(lambda x: 'Month%.2d' % x, range(1, 13))))
sku = pd.concat([sku, month_onehot], axis=1).drop(['Month'], axis=1)
sku.head()

,Agency,SKU,YearMonth,Volume,Price,Sales,Promotions,Soda_Volume,Industry_Volume,Avg_Max_Temp,...,Month03,Month04,Month05,Month06,Month07,Month08,Month09,Month10,Month11,Month12
0,Agency_22,SKU_01,201301,52.2720,1168.903668,1069.166193,99.737475,718394219,492612703,25.845238,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Agency_22,SKU_02,201301,110.7000,1167.000000,1067.257500,99.742500,718394219,492612703,25.845238,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Agency_58,SKU_23,201301,0.0000,0.000000,0.000000,0.000000,718394219,492612703,22.219737,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Agency_48,SKU_07,201301,28.3200,1143.503390,1143.503390,0.000000,718394219,492612703,24.052893,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Agency_22,SKU_05,201301,238.5387,1310.176057,1203.875711,106.300346,718394219,492612703,25.845238,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
pwr_cols = ['Volume', 'Price', 'Sales', 'Promotions', 'Avg_Max_Temp']
std_cols = ['Soda_Volume', 'Industry_Volume']
pwr_scaler = PowerTransformer().fit(sku[pwr_cols])
std_scaler = StandardScaler().fit(sku[std_cols])

pwr_data = pd.DataFrame(pwr_scaler.transform(sku[pwr_cols]), columns=list(map(lambda x: f'tr_{x}', pwr_cols)))
std_data = pd.DataFrame(std_scaler.transform(sku[std_cols]), columns=list(map(lambda x: f'tr_{x}', std_cols)))
sku = pd.concat([sku, pwr_data, std_data], axis=1)
sku.head()

,Agency,SKU,YearMonth,Volume,Price,Sales,Promotions,Soda_Volume,Industry_Volume,Avg_Max_Temp,...,Month10,Month11,Month12,tr_Volume,tr_Price,tr_Sales,tr_Promotions,tr_Avg_Max_Temp,tr_Soda_Volume,tr_Industry_Volume
0,Agency_22,SKU_01,201301,52.2720,1168.903668,1069.166193,99.737475,718394219,492612703,25.845238,...,0.0,0.0,0.0,-0.343140,-0.282551,-0.291021,-0.127001,-0.680355,-1.697382,-0.815995
1,Agency_22,SKU_02,201301,110.7000,1167.000000,1067.257500,99.742500,718394219,492612703,25.845238,...,0.0,0.0,0.0,-0.098724,-0.285118,-0.294154,-0.126965,-0.680355,-1.697382,-0.815995
2,Agency_58,SKU_23,201301,0.0000,0.000000,0.000000,0.000000,718394219,492612703,22.219737,...,0.0,0.0,0.0,-1.508332,-2.358804,-2.217093,-1.730776,-1.663269,-1.697382,-0.815995
3,Agency_48,SKU_07,201301,28.3200,1143.503390,1143.503390,0.000000,718394219,492612703,24.052893,...,0.0,0.0,0.0,-0.533631,-0.316879,-0.169378,-1.730776,-1.158285,-1.697382,-0.815995
4,Agency_22,SKU_05,201301,238.5387,1310.176057,1203.875711,106.300346,718394219,492612703,25.845238,...,0.0,0.0,0.0,0.162987,-0.094812,-0.071109,-0.081727,-0.680355,-1.697382,-0.815995

In [12]:
num_cols = list(filter(lambda x: x.startswith('tr_'), sku.columns))
onehot_cols = sku.columns.to_list()[10:-7]
base_cols = ['Agency', 'SKU', 'YearMonth']

agencies = sorted(sku['Agency'].drop_duplicates())
skues = sorted(sku['SKU'].drop_duplicates())
months = sorted(sku['YearMonth'].drop_duplicates())
len(agencies), len(skues), len(months)

(58, 25, 60)

In [21]:
def make_seq_data(data, target, sku, l_seq, given_list=None):
    target_data = data.loc[data['SKU'] == sku][['YearMonth', 'Agency', target]].sort_values(['Agency', 'YearMonth'])
    seq_data = target_data.pivot(index='Agency', columns='YearMonth', values=target)
    if seq_data.shape[0] != len(agencies): 
        dummy = pd.DataFrame(np.zeros((len(agencies) - seq_data.shape[0], seq_data.shape[1])), index=sorted(set(agencies) - set(seq_data.index)), columns=seq_data.columns)
        seq_data = pd.concat([seq_data, dummy], axis=0).sort_index()
    if seq_data.shape[1] != len(months):
        dummy = pd.DataFrame(np.zeros((seq_data.shape[0], len(months) - seq_data.shape[1])), index=seq_data.index, columns=sorted(set(months) - set(seq_data.columns)))
        seq_data = pd.concat([seq_data, dummy], axis=1)[agencies]
    if given_list is None:
        json_data = []
    else:
        json_data = given_list
    for i in range(l_seq, len(months) - 1):
        single = list(filter(lambda x: x['date'] == months[i], json_data))
        if len(single) == 0:
            single = {'date': months[i]}
        else:
            single = single[0]
        single[f'input_{target[3:]}'] = seq_data[months[i - l_seq:i]].values.tolist()

        if target == 'tr_Volume':
            single['output'] = seq_data[months[i + 1]].values.tolist()
            single[f'date_total_{target[3:]}'] = seq_data[months[i - l_seq:i]].sum(0).values.tolist()
        json_data.append(single)
    return json_data

def make_seq_data_by_date(data, target_name, target_list, l_seq, given_list=None):
    seq_data = data[['YearMonth'] + target_list].drop_duplicates().sort_values(['YearMonth'])
    seq_data.index = seq_data['YearMonth']
    seq_data = seq_data.drop(['YearMonth'], axis=1).T
    if given_list is None:
        json_data = []
    else:
        json_data = given_list
    for i in range(l_seq, len(months) - 1):
        single = list(filter(lambda x: x['date'] == months[i], json_data))
        if len(single) == 0:
            single = {'date': months[i]}
        else:
            single = single[0]
        single[target_name] = seq_data[months[i - l_seq:i]].values.tolist()
        json_data.append(single)
    return json_data

In [22]:
import json 

l_seq = 5
for i, s in enumerate(skues):
    result_list = None
    for c in num_cols:
        result_list = make_seq_data(sku, c, s, l_seq, result_list)
    result_list = make_seq_data_by_date(sku, 'input_month', onehot_cols[-12:], l_seq, result_list)
    result_list = make_seq_data_by_date(sku, 'input_event', onehot_cols[:-12], l_seq, result_list)
    if i == 0:
        all_df = pd.DataFrame(result_list)
        test_idx = list(all_df[all_df['date'] >= 201701].index)
        train_val_idx = sorted(set(np.arange(len(all_df))) - set(test_idx))
        val_idx = np.random.choice(train_val_idx, round(len(train_val_idx) * 0.1), replace=False)
        train_idx = sorted(set(train_val_idx) - set(val_idx))
        print('!!', len(all_df), len(train_idx), len(val_idx), len(test_idx))
    train_list, val_list, test_list = [], [], []
    for j in range(len(result_list)):
        if j in train_idx:
            train_list.append(result_list[j]) 
        elif j in val_idx:
            val_list.append(result_list[j]) 
        else:
            test_list.append(result_list[j]) 
    print(len(result_list), len(train_list), len(val_list), len(test_list))
    with open(f'../sku_seq_data/train_{s}.json', 'w') as f:
        json.dump(train_list, f)
    with open(f'../sku_seq_data/val_{s}.json', 'w') as f:
        json.dump(val_list, f)
    with open(f'../sku_seq_data/test_{s}.json', 'w') as f:
        json.dump(test_list, f)

!! 486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99
486 348 39 99

In [23]:
from datasets import load_dataset

dir_path = '../sku_seq_data'

test_datasets = load_dataset('json', data_files={
    'train': f'{dir_path}/train_SKU_01.json',
    'val': f'{dir_path}/val_SKU_01.json',
    'test': f'{dir_path}/test_SKU_01.json'
})

Downloading data files:   0%|          | 0/3 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating val split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [24]:
test_datasets['val'].data.to_pandas()

,input_Sales,input_Price,date,input_Industry_Volume,input_month,input_Soda_Volume,input_event,output,input_Promotions,input_Avg_Max_Temp,input_Volume,date_total_Volume
0,"[[-0.34976083596813046, -0.297175208173881, -0...","[[-0.31959399799331106, -0.31959399799331106, ...",201306,"[[-0.815994825159276, -1.780953304951829, -0.5...","[[1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0....","[[-1.6973822582794633, -1.2430938326211054, 0....","[[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0...","[0.0030123111434070798, 1.4838825897759795, 1....","[[-0.06984313215772828, -0.30804399805669536, ...","[[-3.1867075105970772, -2.304070510000844, -1....","[[-0.20319756618613685, -0.13898514079066623, ...","[21.515817775289474, 23.795185930569996, 25.81..."
1,"[[-0.009827936860335323, -0.03728707904292913,...","[[-0.10606900471547714, -0.10596213628639016, ...",201504,"[[-0.9508505854145107, -0.33953751894212353, -...","[[0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1....","[[-1.7307390157699118, -1.9784700619688234, -1...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0...","[-0.16040010534177068, 1.60644082355805, 0.973...","[[-0.45341653374466606, -0.30074260230923466, ...","[[-2.1602527204174393, -2.4479086146540388, -3...","[[-0.2580882813513545, -0.2248699895985046, -0...","[25.952057041409425, 29.93195656420496, 24.646..."
2,"[[-0.03728707904292913, -0.010112663948543807,...","[[-0.10596213628639016, -0.10714835486610493, ...",201505,"[[-0.33953751894212353, -0.7212976253478683, -...","[[0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0....","[[-1.9784700619688234, -1.13718317135869, -1.7...","[[0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [0, 1, 0, 0...","[-0.17991442257133952, 1.5962281121132087, 1.0...","[[-0.30074260230923466, -0.45972414653242244, ...","[[-2.4479086146540388, -3.2930163707434534, -2...","[[-0.2248699895985046, -0.4152883740662643, -0...","[29.93195656420496, 24.64682617641008, 26.0961..."
3,"[[0.012377944875144034, 0.05468851882364097, 0...","[[0.04555799718624553, 0.05884429173662959, 0....",201511,"[[0.09614785559634217, 0.47720125235773275, 0....","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.6147363200415271, 0.5868100028553552, 0.30...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.42267840264153483, 1.474197813497403, 0.85...","[[0.25021646842973716, 0.16603079639528556, 0....","[[0.6714915969185684, 0.4426525407894491, 0.52...","[[-0.17991442257133952, -0.032173046361333404,...","[28.969255231550743, 29.266073751167756, 28.46..."
4,"[[-0.08217069762815091, -0.05040164782632046, ...","[[0.09759336014062375, 0.09983213518841616, 0....",201603,"[[0.004487644940484917, 0.2798293370393837, 0....","[[0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0....","[[-1.1468358701915122, -0.6689536086580722, -0...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1...","[-0.2653413895479013, 1.3430506077806033, 0.79...","[[0.684276360195466, 0.615047939438193, 0.4229...","[[-0.7312799601774264, -1.377344437792543, -2....","[[-0.16001294011479783, -0.3277330578929649, -...","[25.45443462830821, 23.949159759960132, 26.926..."
5,"[[0.13525737449698236, 0.14438780531999892, 0....","[[0.15712990249563433, 0.17703242002226552, 0....",201609,"[[0.7196528045193554, 0.18126109805580626, -0....","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.17237605974115866, 1.3083691980386547, 0.7...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.29313226753041943, 1.4300546727635344, 0.4...","[[0.30698677443133315, 0.3556901089900615, 0.4...","[[-0.28473640251701493, 0.4634962209945592, 0....","[[-0.2653413895479013, -0.3627354569960459, -1...","[28.702085277077114, 29.39506786961516, 26.927..."
6,"[[-0.3069265025798241, -0.4131312348502818, -0...","[[-0.1938142508012902, -0.1938142508012902, -0...",201405,"[[-1.9049844338047708, -0.9948763204482096, -1...","[[0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0....","[[-0.8395660274059293, -1.1180301096560725, -1...","[[0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [0, 1, 0, 0...","[-0.26481823319745723, 1.5570748671770431, 1.1...","[[0.3144124810783784, 0.5996068237645911, 0.02...","[[-3.0461209871524244, -2.568147020606126, -1....","[[-0.11776631322842963, -0.130699771842593, -0...","[27.362616976142725, 23.027616033039756, 25.84..."
7,"[[-0.013304191799630279, -0.07939397687752128,...","[[-0.12712044481761242, -0.10339006822814846, ...",201501,"[[-0.33707838821373104, -2.0813018503052922, -...","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.2069051357040197, -1.0712597993349413, -0....","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.30821321411146274, 1.4468552593017099, 0.9...","[[-0.5995868296864381, -0.09149770653164048, -...","[[0.31055482251993505, -0.0695101387020347, -0...","[[-0.1089530218434949, -0.12963328119373776, -...","[28.15441291279994, 26.616403294848237, 26.951..."
8,"[[-0.07939397687752128, 0.0008654315025402296,...","[[-0.10339006822814846, -0.10480745175384668, ...",201502,"[[-2.0813018503052922, -1.6713155663616668, -0...","[[0.0, 0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0....","[[-1.0712597993349413, -0.7711082215541483, -1...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.17705926917385736, 1.3809292456967523, 0.9...","[[-0.09149770653164048, -0.5100369297950145, -...","[[-0.0695101387020347, -0.10195087519089606, -...","[[-0.12963328119373776, -0.09100231330786468, ...","[26.616403294848237, 26.951049138669216, 25.95..."
9,"[[0.023290000842201578, -0.08217069762815091, ...","[[0.036987345339156145, 0.09759336014062375, 0...",201602,"[[0.15996734501537893, 0.004487644940484917, 0...","[[0.0, 0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0....","[[-1.3884089980527943, -1.1468358701915122, -0...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.1710183235776903, 1.3530946926952818, 0.73...","[[0.17928493626184464, 0.684276360195466, 0.61...","[[0.24267387396785034, -0.7312799601774264, -1...","[[-0.12121540435629743, -0.16001294011479783, ...","[27.065937517947198, 25.45443462830821, 23.949..."
10,"[[0.03550764594046661, 0.038350077264154944, 0...","[[0.12349356046537048, 0.12243417262081889, 0....",201606,"[[-0.42195498464605574, -0.1785079924218855, 0...","[[1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0....","[[-0.8144042775615298, -1.556480451914887, 0.0...","[[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0...","[-0.3302531581805874, 1.511574470420295, 0.985...","[[0.4712028001192704, 0.45980050585367804, 0.4...","[[-3.294107152354895, -1.3556015194098807, -0....","[[-0.32212977776228935, -0.33987249606493786, ...","[20.525523700852517, 22.128050585965536, 26.68..."
11,"[[0.038350077264154944, 0.03163965800582643, 0...","[[0.12243417262081889, 0.12308487008066403, 0....",201607,"[[-0.1785079924218855, 0.2007247407754632, 0.7...","[[0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[-1.556480451914887, 0.018987548382697183, 0....","[[0, 1, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0...","[-0.20014664551133743, 1.4746421309337892, 0.7...","[[0.45980050585367804, 0.4802550305992197, 0.3...","[[-1.3556015194098807, -0.7881839916015754, -0...","[[-0.33987249606493786, -0.1710183235776903, -...","[22.128050585965536, 26.680802584400166, 28.70..."
12,"[[-0.34976083596813046, -0.297175208173881, -0...","[[-0.31959399799331106, -0.31959399799331106, ...",201306,"[[-0.815994825159276, -1.780953304951829, -0.5...","[[1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0....","[[-1.6973822582794633, -1.2430938326211054, 0....","[[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0...","[0.0030123111434070798, 1.4838825897759795, 1....","[[-0.06984313215772828, -0.30804399805669536, ...","[[-3.1867075105970772, -2.304070510000844, -1....","[[-0.20319756618613685, -0.13898514079066623, ...","[21.515817775289474, 23.795185930569996, 25.81..."
13,"[[-0.2269869576669844, -0.22571597907158047, 0...","[[-0.1938142508012902, -0.1938142508012902, -0...",201408,"[[0.21064275389353995, -0.470301418110751, 0.4...","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[-0.2929564995702932, 0.28801481457134864, 0....","[[0, 1, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0...","[-0.12963328119373776, 1.580928121243408, 1.18...","[[0.05002808615752572, 0.045328402528880055, -...","[[-1.4048547883779214, -0.49138357817832085, 0...","[[-0.05761247896135414, -0.24698910525608428, ...","[28.796006949454657, 31.04171773541605, 26.392..."
14,"[[-0.22571597907158047, 0.015304803652139912, ...","[[-0.1938142508012902, -0.1552459636965537, -0...",201409,"[[-0.470301418110751, 0.4893321284803946, 0.15...","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.28801481457134864, 0.46359785392872443, 0....","[[1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.09100231330786468, 1.6451813076783006, 1.2...","[[0.045328402528880055, -1.306461752633598, -1...","[[-0.49138357817832085, 0.23459313148407338, 1...","[[-0.24698910525608428, -0.6104572439347202, -...","[31.04171773541605, 26.39249958453188, 28.5949..."
15,"[[-0.07334225463616476, 0.012377944875144034, ...","[[-0.02165051822042779, 0.04555799718624553, 0...",201510,"[[0.45121667568539414, 0.09614785559634217, 0....","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.9794523752860426, 0.6147363200415271, 0.58...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.3277330578929649, 1.440463561279914, 0.781...","[[0.2545557927901761, 0.25021646842973716, 0.1...","[[-0.08855291655013701, 0.6714915969185684, 0....","[[-0.16040010534177068, -0.17991442257133952, ...","[31.25434508391197, 28.969255231550743, 29.266..."
16,"[[0.13525737449698236, 0.14438780531999892, 0....","[[0.15712990249563433, 0.17703242002226552, 0....",201609,"[[0.7196528045193554, 0.18126109805580626, -0....","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.17237605974115866, 1.3083691980386547, 0.7...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.29313226753041943, 1.4300546727635344, 0.4...","[[0.30698677443133315, 0.3556901089900615, 0.4...","[[-0.28473640251701493, 0.4634962209945592, 0....","[[-0.2653413895479013, -0.3627354569960459, -1...","[28.702085277077114, 29.39506786961516, 26.927..."
17,"[[-0.297175208173881, -0.23862049103534566, -0...","[[-0.31959399799331106, -0.26849200925357863, ...",201307,"[[-1.780953304951829, -0.5508999378427738, -0....","[[0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[-1.2430938326211054, 0.5239170416192184, -0....","[[0, 1, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0...","[0.02782706467876218, 1.4536466502851628, 1.19...","[[-0.30804399805669536, -0.29039181597050784, ...","[[-2.304070510000844, -1.0108161436008527, -0....","[[-0.13898514079066623, -0.03542590367633548, ...","[23.795185930569996, 25.819652291029776, 27.13..."
18,"[[-0.4131312348502818, -0.2210713939520793, -0...","[[-0.1938142508012902, -0.1938142508012902, -0...",201406,"[[-0.9948763204482096, -1.8828707213646627, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0....","[[-1.1180301096560725, -1.4922516529252765, -0...","[[0, 0, 0, 1, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0...","[-0.17061927149727282, 1.6149030239415203, 1.2...","[[0.5996068237645911, 0.027992918490600108, 0....","[[-2.568147020606126, -1.3583286429935628, -1....","[[-0.130699771842593, -0.061985418605928426, -...","[23.027616033039756, 25.84883414475663, 28.796..."
19,"[[0.023290000842201578, -0.08217069762815091, ...","[[0.036987345339156145, 0.09759336014062375, 0...",201602,"[[0.15996734501537893, 0.004487644940484917, 0...","[[0.0, 0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0....","[[-1.3884089980527943, -1.1468358701915122, -0...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.1710183235776903, 1.3530946926952818, 0.73...","[[0.17928493626184464, 0.684276360195466, 0.61...","[[0.24267387396785034, -0.7312799601774264, -1...","[[-0.12121540435629743, -0.16001294011479783, ...","[27.065937517947198, 25.45443462830821, 23.949..."
20,"[[-0.23862049103534566, -0.17789612348654146, ...","[[-0.26849200925357863, -0.2051273837545981, -...",201308,"[[-0.5508999378427738, -0.18338519070379988, 0...","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.5239170416192184, -0.1674368423147106, 0.1...","[[1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.0016664239828886214, 1.3862791784997093, 1...","[[-0.29039181597050784, -0.20987615705206164, ...","[[-1.0108161436008527, -0.2435068677505285, 0....","[[-0.03542590367633548, -0.0026592208727951473...","[25.819652291029776, 27.133211696626752, 27.96..."
21,"[[-0.1552655668124227, -0.170288472856005, -0....","[[-0.19432656883063942, -0.19383877038577732, ...",201402,"[[-1.4260616195032525, -1.0055470683183383, -1...","[[0.0, 0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0....","[[-0.7869980933018907, -0.7609939009147476, -0...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.05761247896135414, 1.5934090107275085, 1.1...","[[-0.2545916559131743, -0.1812270735690325, -0...","[[-0.40888827319401216, -0.602100208606848, -2...","[[-0.0016664239828886214, 0.002032356061823214...","[21.83894369499133, 25.106777261327746, 24.000..."
22,"[[-0.18539997598625568, -0.3069265025798241, -...","[[-0.1938142508012902, -0.1938142508012902, -0...",201404,"[[-1.7328712852537478, -1.9049844338047708, -0...","[[0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1....","[[-0.5744548907931913, -0.8395660274059293, -1...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0...","[-0.6104572439347202, 1.5072910263681234, 1.25...","[[-0.11465456533698344, 0.3144124810783784, 0....","[[-2.4593137790300967, -3.0461209871524244, -2...","[[-0.14821760705331352, -0.11776631322842963, ...","[24.00010742847141, 27.362616976142725, 23.027..."
23,"[[-0.4131312348502818, -0.2210713939520793, -0...","[[-0.1938142508012902, -0.1938142508012902, -0...",201406,"[[-0.9948763204482096, -1.8828707213646627, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0....","[[-1.1180301096560725, -1.4922516529252765, -0...","[[0, 0, 0, 1, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0...","[-0.17061927149727282, 1.6149030239415203, 1.2...","[[0.5996068237645911, 0.027992918490600108, 0....","[[-2.568147020606126, -1.3583286429935628, -1....","[[-0.130699771842593, -0.061985418605928426, -...","[23.027616033039756, 25.84883414475663, 28.796..."
24,"[[-0.2210713939520793, -0.2269869576669844, -0...","[[-0.1938142508012902, -0.1938142508012902, -0...",201407,"[[-1.8828707213646627, 0.21064275389353995, -0...","[[0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[-1.4922516529252765, -0.2929564995702932, 0....","[[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0...","[-0.1089530218434949, 1.6193490108312698, 1.17...","[[0.027992918490600108, 0.05002808615752572, 0...","[[-1.3583286429935628, -1.4048547883779214, -0...","[[-0.061985418605928426, -0.05761247896135414,...","[25.84883414475663, 28.796006949454657, 31.041..."
25,"[[-0.22571597907158047, 0.015304803652139912, ...","[[-0.1938142508012902, -0.1552459636965537, -0...",201409,"[[-0.470301418110751, 0.4893321284803946, 0.15...","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.28801481457134864, 0.46359785392872443, 0....","[[1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.09100231330786468, 1.6451813076783006, 1.2...","[[0.045328402528880055, -1.306461752633598, -1...","[[-0.49138357817832085, 0.23459313148407338, 1...","[[-0.24698910525608428, -0.6104572439347202, -...","[31.04171773541605, 26.39249958453188, 28.5949..."
26,"[[0.015304803652139912, 0.02880941640929269, 0...","[[-0.1552459636965537, -0.1437394817665604, -0...",201410,"[[0.4893321284803946, 0.15772243619461868, 0.1...","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.46359785392872443, 0.17832182734044721, -0...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.2580882813513545, 1.4057214386055603, 1.04...","[[-1.306461752633598, -1.2938531130134387, -1....","[[0.23459313148407338, 1.190814617769797, 0.38...","[[-0.6104572439347202, -0.26481823319745723, -...","[26.39249958453188, 28.5949229659824, 28.03818..."
27,"[[-0.07939397687752128, 0.0008654315025402296,...","[[-0.10339006822814846, -0.10480745175384668, ...",201502,"[[-2.0813018503052922, -1.6713155663616668, -0...","[[0.0, 0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0....","[[-1.0712597993349413, -0.7711082215541483, -1...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.17705926917385736, 1.3809292456967523, 0.9...","[[-0.09149770653164048, -0.5100369297950145, -...","[[-0.0695101387020347, -0.10195087519089606, -...","[[-0.12963328119373776, -0.09100231330786468, ...","[26.616403294848237, 26.951049138669216, 25.95..."
28,"[[-0.08217069762815091, -0.05040164782632046, ...","[[0.09759336014062375, 0.09983213518841616, 0....",201603,"[[0.004487644940484917, 0.2798293370393837, 0....","[[0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0....","[[-1.1468358701915122, -0.6689536086580722, -0...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1...","[-0.2653413895479013, 1.3430506077806033, 0.79...","[[0.684276360195466, 0.615047939438193, 0.4229...","[[-0.7312799601774264, -1.377344437792543, -2....","[[-0.16001294011479783, -0.3277330578929649, -...","[25.45443462830821, 23.949159759960132, 26.926..."
29,"[[-0.16046159909041288, -0.1680923354221898, -...","[[-0.20027556978082703, -0.19428693944011255, ...",201310,"[[0.12458647383519929, -0.19462619506553724, -...","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.16896378018072036, 0.48977697897179084, 0....","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.14821760705331352, 1.3088426260400814, 1.0...","[[-0.2648355880913132, -0.19375620558474163, -...","[[0.2259609010762412, 1.2292308856046466, 0.21...","[[0.057205773625883055, 0.06717609048596067, 0...","[27.967933221545174, 25.42770484151908, 25.484..."
30,"[[-0.170288472856005, -0.18539997598625568, -0...","[[-0.19383877038577732, -0.1938142508012902, -...",201403,"[[-1.0055470683183383, -1.7328712852537478, -1...","[[0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0....","[[-0.7609939009147476, -0.5744548907931913, -0...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1...","[-0.24698910525608428, 1.6020963868115468, 1.1...","[[-0.1812270735690325, -0.11465456533698344, 0...","[[-0.602100208606848, -2.4593137790300967, -3....","[[0.0020323560618232144, -0.14821760705331352,...","[25.106777261327746, 24.00010742847141, 27.362..."
31,"[[-0.013304191799630279, -0.07939397687752128,...","[[-0.12712044481761242, -0.10339006822814846, ...",201501,"[[-0.33707838821373104, -2.0813018503052922, -...","[[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....","[[0.2069051357040197, -1.0712597993349413, -0....","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...","[-0.30821321411146274, 1.4468552593017099, 0.9...","[[-0.5995868296864381, -0.09149770653164048, -...","[[0.31055482251993505, -0.0695101387020347, -0...","[[-0.1089530218434949, -0.12963328119373776, -...","[28.15441291279994, 26.616403294848237, 26.951..."
32,"[[-0.011780320975324566, -0.10728547827119136,...","[[-0.10530278799460975, -0.10472339497927904, ...",201507,"[[-2.0034473907520804, -0.45251115542977716, -...","[[0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[-1.7145117145599766, 0.2556783974564628, 0.1...","[[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0...","[-0.14044616685005867, 1.5540106084800045, 0.9...","[[-0.43617449142842224, 0.013597252723341354, ...","[[-2.061988839189056, -2.207941850583773, -1.0...","[[-0.30821321411146274, -0.17705926917385736, ...","[26.096187329608277, 33.12434559756485, 31.241..."
33,"[[-0.08217069762815091, -0.05040164782632046, ...","[[0.09759336014062375, 0.09983213518841616, 0....",201603,"[[0.004487644940484917, 0.2798293370393837, 0....","[[0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0....","[[-1.1468358701915122, -0.6689536086580722, -0...","[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1...","[-0.2653413895479013, 1.3430506077806033, 0.79...","[[0.684276360195466, 0.615047939438193, 0.4229...","[[-0.7312799601774264, -1.377344437792543, -2....","[[-0.16001294011479783, -0.3277330578929649, -...","[25.45443462830821, 23.949159759960132, 26.926..."